baseURL = "https://how-to-processmaker.netlify.app/"
languageCode = "en-us"
title = "ProcessMaker Snippets and Tutorials"


# Change the default theme
theme = "learn-theme"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


# [params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
#themeVariant = "blue"
[params]
  editURL = "https://github.com/aghwotu/how-to-processmaker/edit/master/content/"
  description = "ProcessMaker Snippets and Tutorials"
  author = "Aghwotu Ovuoke"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false


[[menu.shortcuts]]
name = "Maintained by Aghwotu Ovuoke"
identifier = "twitter"
url = "https://twitter.com/ediri_aghwotu"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "github"
url = "https://github.com/aghwotu/how-to-processmaker"
